name: Deploy Infra

on: push

env:
  AWS_REGION: us-east-1
  IAM_ROLE: arn:aws:iam::160071257600:role/ss-iac-lab-github-actions-role

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@2ec54502e3e7b5d9591613811da6daded35caa19
        with:
          role-session-name: GitHubActionsSession
          role-to-assume: ${{ env.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get aws identity
        run: aws sts get-caller-identity

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -reconfigure
        continue-on-error: false

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"
        continue-on-error: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"
        continue-on-error: false


